/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    File: typeof import('./src/components/File.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Imgx: typeof import('./src/components/Imgx.vue')['default']
    Overlay: typeof import('./src/components/Layer/Overlay.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    PulseBlock: typeof import('./src/components/PulseBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    System: typeof import('./src/components/System/System.vue')['default']
  }
}
